#include <stdio.h>
#include "pcan_can.h"

/*
 * Phase 2 CAN stub.
 *
 * There is no real CAN controller wired up yet (that lands in Phase 3 with the
 * HPM5300 MCAN driver behind this same pcan_can.h interface). Transmitted
 * frames are silently consumed here.
 *
 * NOTE on echoes: TX-completion echoes are NOT produced by this stub.
 * pcan_protocol.c's pcan_decode_data_frame() already echoes a frame back to
 * the host (with the correct client/echo-id byte) whenever the incoming record
 * carries the SRR (self-receive) bit -- that is how the Linux peak_usb driver
 * requests TX completion. A stub echo on top of that would deliver duplicate
 * echoes with a bogus echo id (0) and confuse the driver's echo_skb matching.
 */

static struct
{
  uint16_t brp;
  uint8_t  tseg1;
  uint8_t  tseg2;
  uint8_t  sjw;
  uint8_t  bus_active;
  uint8_t  silent;
  uint8_t  loopback;
  void (*rx_cb)( can_message_t * );
  void (*can_err_cb)( uint8_t err, uint8_t rx_err, uint8_t tx_err );
}
can_dev = { 0 };

void pcan_can_init( void )
{
  /* no CAN hardware in Phase 2 */
}

void pcan_can_poll( void )
{
  /* no CAN hardware in Phase 2 */
}

void pcan_can_install_rx_callback( void (*cb)( can_message_t * ) )
{
  can_dev.rx_cb = cb;
}

void pcan_can_install_error_callback( void (*cb)( uint8_t, uint8_t, uint8_t ) )
{
  can_dev.can_err_cb = cb;
}

void pcan_can_set_bitrate( uint16_t brp, uint8_t tseg1, uint8_t tseg2, uint8_t sjw )
{
  can_dev.brp   = brp;
  can_dev.tseg1 = tseg1;
  can_dev.tseg2 = tseg2;
  can_dev.sjw   = sjw;
  printf( "[pcan_can] set_bitrate brp=%u tseg1=%u tseg2=%u sjw=%u\r\n",
          (unsigned)brp, (unsigned)tseg1, (unsigned)tseg2, (unsigned)sjw );
}

void pcan_can_set_bus_active( uint16_t mode )
{
  can_dev.bus_active = (uint8_t)mode;
  printf( "[pcan_can] set_bus_active mode=%u\r\n", (unsigned)mode );
}

void pcan_can_set_silent( uint8_t silent_mode )
{
  can_dev.silent = silent_mode;
  printf( "[pcan_can] set_silent=%u\r\n", (unsigned)silent_mode );
}

void pcan_can_set_loopback( uint8_t loopback )
{
  can_dev.loopback = loopback;
  printf( "[pcan_can] set_loopback=%u\r\n", (unsigned)loopback );
}

int pcan_can_send_message( const can_message_t *msg )
{
  if( !msg )
    return 0;

  /* Phase 2: frame is consumed here; no CAN hardware yet. The host-visible
   * TX-completion echo (when requested via the SRR bit) is generated by the
   * protocol layer itself -- see the NOTE above. */
  return 0;
}
